w_userflow_featurestore:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10000
      schema: silver
      user: spark
      auth: NOSASL
      threads: 4
      connect_timeout: 30
      retries: 3
      use_ssl: false
      session_properties:
        spark.sql.catalog.iceberg: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.iceberg.catalog-impl: org.apache.iceberg.hadoop.HadoopCatalog
        spark.sql.catalog.iceberg.warehouse: s3a://w-userflow-featurestore/iceberg/